#!/usr/bin/env python

import os
import shutil
import torch
from diffusers import StableDiffusionPipeline


model_id = "Linaqruf/anything-v3.0"
MODEL_CACHE = "diffusers-cache"

if os.path.exists(MODEL_CACHE):
    shutil.rmtree(MODEL_CACHE)
os.makedirs(MODEL_CACHE, exist_ok=True)


pipe = StableDiffusionPipeline.from_pretrained(
    model_id, 
    revision="diffusers", 
    torch_dtype=torch.float16,   
    cache_dir=MODEL_CACHE,
)

