#!/usr/bin/env python

import os
import shutil
import torch
from diffusers import StableDiffusionPanoramaPipeline


MODEL_ID = "stabilityai/stable-diffusion-2-base"
MODEL_CACHE = "diffusers-cache"

if os.path.exists(MODEL_CACHE):
    shutil.rmtree(MODEL_CACHE)
os.makedirs(MODEL_CACHE, exist_ok=True)


pipe = StableDiffusionPanoramaPipeline.from_pretrained(
    MODEL_ID,
    torch_dtype=torch.float16,
    cache_dir=MODEL_CACHE,
)
